services:
    app:
        build:
            context: .
            dockerfile: Docker/Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - ./:/var/www
        ports:
            - '8000:80' # Changed port to map to Nginx's port 80
        env_file:
            - .env

    nginx:
        # Added Nginx service
        image: nginx:alpine
        container_name: laravel_nginx
        restart: unless-stopped
        ports:
            - '80:80' # This is the port your browser will connect to
        volumes:
            - ./:/var/www
            - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - app

    cloudflared:
        image: cloudflare/cloudflared:latest
        container_name: laravel_cloudflared
        restart: unless-stopped
        command: tunnel --no-autoupdate run --token $CLOUDFLARE_TOKEN
        env_file:
            - .env
        depends_on:
            - nginx

volumes:
    laravel_db_data:
        driver: local
