name: Test Laravel App

on:
    push:
        branches: ['*']
    pull_request:
        branches: ['*']

jobs:
    test:
        runs-on: ubuntu-latest
        env: # Define environment variables for the job, making secrets available
            REVERB_APP_ID: ${{ secrets.REVERB_APP_ID || 'test_app_id' }}
            REVERB_APP_KEY: ${{ secrets.REVERB_APP_KEY || 'test_app_key' }}
            REVERB_APP_SECRET: ${{ secrets.REVERB_APP_SECRET || 'test_app_secret' }}

        steps:
            - uses: actions/checkout@v4

            - name: Set up PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: mbstring, pdo, sqlite, pdo_sqlite, pcntl
                  coverage: none

            - name: Install Composer dependencies
              run: composer install --no-interaction --prefer-dist --optimize-autoloader

            - name: Install NPM dependencies and build
              run: |
                  npm install
                  npm install
                  npm run build

            - name: Copy .env.dev.example to .env
              run: cp .env.dev.example .env

            - name: Update .env with Reverb test configuration # This step updates the .env file
              run: |
                  echo "" >> .env # Add a newline for separation if .env.dev.example doesn't end with one
                  echo "# Reverb Configuration for Testing (from GitHub Actions)" >> .env

                  echo "REVERB_APP_ID=${REVERB_APP_ID}" >> .env
                  echo "REVERB_APP_KEY=${REVERB_APP_KEY}" >> .env
                  echo "REVERB_APP_SECRET=${REVERB_APP_SECRET}" >> .env
                  echo "Generated .env for testing:"
                  cat .env

            - name: Generate Laravel key
              run: php artisan key:generate

            - name: Run migrations
              run: php artisan migrate --force --seed

            - name: Start Laravel server (background)
              run: php artisan serve --host=127.0.0.1 --port=8000 &

            - name: Start Reverb (background)
              run: php artisan reverb:start &

            - name: Wait for services to be ready
              run: sleep 5

            - name: Run tests
              run: php artisan test
